### PR TITLE
Implement device as usbhid instead of serial

### PR DESCRIPTION
**Pull request by trunet**
Hello,

First of all, thanks for the amazing work here.

For some reason, my PowerWalker ATS is not recognized when plugged directly through USB. Your library works fine if I use a max232 connected to powerwalker ATS serial and then usb-serial dongle to my computer.

Therefore, I started doing some research and was successful using the usbhid directly on a file descriptor.

Let me know if you want any changes.

### CODE REVIEW

**Comment by thomasjsn** [comment]
Oh, nice! I've been wanting to do this for a long time, thanks :) I'm in the middle of a move now, and my server rack is in pieces ATM. But I'll test this once I start putting it back together. It will be nice to get rid of the USB-serial adapters :)

**Comment by trunet** [comment]
@thomasjsn a question to you (unrelated to this). do you remember connecting directly to the USB port on the powerwalker and feel some residual current running through it?

I have this error on my server from time to time:

```
[43311.100676] usb 3-1-port1: disabled by hub (EMI?), re-enabling...
[43311.105773] usb 3-1.1: USB disconnect, device number 3
[43311.427887] usb 3-1.1: new low-speed USB device number 5 using xhci-hcd
[43311.563695] usb 3-1.1: New USB device found, idVendor=0665, idProduct=5161, bcdDevice= 0.02
[43311.563718] usb 3-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[43311.563734] usb 3-1.1: Product: USB to Serial
[43311.563749] usb 3-1.1: Manufacturer: INNO TECH
[43311.626273] hid-generic 0003:0665:5161.0003: hiddev96,hidraw1: USB HID v1.00 Device [INNO TECH USB to Serial] on usb-xhci-hcd.8.auto-1.1/input0
```

**Comment by thomasjsn** [comment]
What do you mean "feel some residual current running through it"? Like tingling when touching it?

Is that error the ATS, or PDU, connected using HID serial and dropping out and getting reconnected from time to time?

**Comment by trunet** [comment]
yeah, like tingling when touching.

I don't have the PDU, only the ATS and the ATS is having that. The HID dropping might be related, but I'm not sure. I open a ticket with the manufacturer to see if they can help me with that.

**Comment by thomasjsn** [comment]
> yeah, like tingling when touching.

That is weird, maybe measure if there any earth leakage on it?

> I don't have the PDU, only the ATS and the ATS is having that. The HID dropping might be related, but I'm not sure. I open a ticket with the manufacturer to see if they can help me with that.

I haven't really tried the USB port on either the ATS og PDU, I've been using the serial port and a serial-USB adapter. That has not been dropping out. But I'll keep an eye out for it.

I do use the HID USB for a Powerwalker UPS, and that did drop out. I had to set some additional parameters to get it stable.

```
maxretry = 3
retrydelay = 5
pollinterval = 5
synchronous = yes
```

I think `synchronous` was the key

```
# synchronous: optional.  The driver work by default in asynchronous
#              mode (i.e *synchronous=no*).  This means that all data
#              are pushed by the driver on the communication socket to
#              upsd (Unix socket on Unix, Named pipe on Windows) without
#              waiting for these data to be actually consumed.  With
#              some HW, such as ePDUs, that can produce a lot of data,
#              asynchronous mode may cause some congestion, resulting in
#              the socket to be full, and the driver to appear as not
#              connected.  By enabling the 'synchronous' flag
#              (value = 'yes'), the driver will wait for data to be
#              consumed by upsd, prior to publishing more.  This can be
#              enabled either globally or per driver.
```

Maybe it gets overwhelmed at times and doesn't handle it very well?

**Comment by trunet** [comment]
These are NUT variables that I'm not using.

Unfortunately the ATS doesn't have a NUT driver, but should be straight forward to implement it there. There're some similar drivers like [voltronic](https://github.com/networkupstools/nut/blob/14301bdbdf586d31c3e80a97a3e0eb04c69326b5/drivers/nutdrv_qx_voltronic.c).

**Comment by thomasjsn** [comment]
> These are NUT variables that I'm not using.
> 
> Unfortunately the ATS doesn't have a NUT driver, but should be straight forward to implement it there. There're some similar drivers like [voltronic](https://github.com/networkupstools/nut/blob/14301bdbdf586d31c3e80a97a3e0eb04c69326b5/drivers/nutdrv_qx_voltronic.c).

Yes, I was just thinking that the root cause might be similar. But again, maybe not, since the USB device is actually dropping from the OS.

**Comment by thomasjsn** [comment]
On my Raspberry Pi I had to add:

    KERNEL=="hidraw*", GROUP=="dialout", MODE="0664"

to `/etc/udev/rules.d/99-com.rules` and run `sudo udevadm trigger` to get access to `/dev/hidrawX`

**Comment by thomasjsn** [comment]
I finally got around to test this :) I am successfully pulling data from both my PDU and ATS through the HID device. I'm just going to run it for a while to see if it's stable :)

**Comment by thomasjsn** [comment]
Looks good :)

**Pull request merged**
